Fixed aiming in house && bullets being destroyed in the house
Wardergrip/kenneyjam23 pull request #44
Opened 2023-08-03 12:03 UTC by Twannes-Claes

2023-08-03 12:19 UTC, Wardergrip requested changes
Make sure debug.logs are gone before they get into main to prevent the console being clogged with unimportant log messages.

Will test functionality soon

2023-08-03 12:19 UTC, Wardergrip commented on Kenneyjam23/Assets/Scripts/Player/Bullet.cs
> +        Debug.Log(other.gameObject.name);
```suggestion
```

2023-08-03 12:19 UTC, Wardergrip commented on Kenneyjam23/Assets/Scripts/Player/PlayerController.cs
> +        //Debug.Log(hit.transform.name);
```suggestion  
```

2023-08-03 12:52 UTC, Wardergrip commented
Aiming in house seems fine and bullets seem fine in house. So functionality looks fine to me.

2023-08-25 10:44 UTC, Twannes-Claes reviewed
Very good

2023-08-25 10:45 UTC, merged